# Generated by Django 5.2.1 on 2025-05-27 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-plays', '-created_at'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM (темп)'),
        ),
        migrations.AddField(
            model_name='track',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Настроение'),
        ),
        migrations.AddField(
            model_name='track',
            name='suitable_for_time',
            field=models.CharField(blank=True, choices=[('morning', 'Утро'), ('day', 'День'), ('evening', 'Вечер'), ('any', 'Любое время')], default='any', max_length=20, null=True, verbose_name='Подходит для времени суток'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='core.PlaylistTrack', to='core.track'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Hip-Hop', 'Hip-Hop'), ('Electronic', 'Electronic'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('R&B', 'R&B'), ('Country', 'Country')], max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков (глобальное)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='musician',
            field=models.ForeignKey(limit_choices_to={'is_musician': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_by_musician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='plays',
            field=models.IntegerField(default=0, verbose_name='Количество прослушиваний (глобальное)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='core.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='UserTrackInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('LIKE', 'Лайк'), ('UNLIKE', 'Дизлайк'), ('PLAY_START', 'Начало прослушивания'), ('PLAY_FULL', 'Полное прослушивание'), ('SKIP_EARLY', 'Пропуск в начале'), ('SKIP_MIDDLE', 'Пропуск в середине'), ('ADD_PLAYLIST', 'Добавление в плейлист'), ('REMOVE_PLAYLIST', 'Удаление из плейлиста')], max_length=20, verbose_name='Тип взаимодействия')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время взаимодействия')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='core.track', verbose_name='Трек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя с треком',
                'verbose_name_plural': 'Взаимодействия пользователей с треками',
                'ordering': ['-timestamp'],
            },
        ),
    ]
