# Generated by Django 5.2.1 on 2025-05-12 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('listen_duration', models.PositiveIntegerField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listened_at'],
                'unique_together': {('user', 'track', 'listened_at')},
            },
        ),
    ]
